#!/usr/bin/env python3
"""
Build app/src/main/assets/ca_public_keys.json for TapRead's offline CDA verification.

Source: the Proxmark3 (RRG/Iceman) EMV CA public key table `capk.txt`, whose format is
    RID  index  expiry  rsa  exponent  modulus  sha1  hash
where `hash` = SHA-1(RID || index || modulus || exponent) — the same EMV CA key check
value TapRead validates. This script recomputes that hash for every entry and only keeps
keys whose modulus/exponent hash matches, so a corrupted or mistyped source line is dropped
rather than shipped. Run it to regenerate the asset; nothing is hand-typed.

Usage:
    python3 scripts/build_ca_public_keys.py            # download from SOURCE_URL
    python3 scripts/build_ca_public_keys.py path.txt   # use a local capk.txt
"""
import hashlib
import json
import os
import sys
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/RfidResearchGroup/proxmark3/master/client/resources/capk.txt"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO_ROOT, "app", "src", "main", "assets", "ca_public_keys.json")


def strip(s: str) -> str:
    return s.replace(":", "").replace(" ", "").upper()


def load(source: str) -> str:
    if source and os.path.exists(source):
        with open(source, "r", encoding="utf-8") as f:
            return f.read()
    print(f"Downloading {SOURCE_URL}")
    with urllib.request.urlopen(SOURCE_URL, timeout=30) as r:
        return r.read().decode("utf-8")


def emv_checksum(rid: str, index: str, modulus: str, exponent: str) -> str:
    data = bytes.fromhex(rid) + bytes.fromhex(index) + bytes.fromhex(modulus) + bytes.fromhex(exponent)
    return hashlib.sha1(data).hexdigest().upper()


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else ""
    text = load(source)

    kept, bad_hash, skipped = [], [], 0
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        f = line.split()
        # Expect: RID index expiry rsa exponent modulus sha1 hash
        if len(f) < 8 or f[3].lower() != "rsa" or f[6].lower() != "sha1":
            skipped += 1
            continue
        rid, index, exponent, modulus, published = strip(f[0]), strip(f[1]), strip(f[4]), strip(f[5]), strip(f[7])
        try:
            computed = emv_checksum(rid, index, modulus, exponent)
        except ValueError:
            skipped += 1
            continue
        if computed != published:
            bad_hash.append((rid, index, published, computed))
            continue
        kept.append({"rid": rid, "index": index, "modulus": modulus, "exponent": exponent, "checksum": computed})

    # Report duplicate (RID, index) pairs — different moduli under the same index do occur
    # (historical / rotated keys). We keep all of them; the verifier tries each candidate.
    seen = {}
    dupes = {}
    for k in kept:
        key = (k["rid"], k["index"])
        if key in seen:
            dupes.setdefault(key, {seen[key]}).add(k["modulus"])
        seen[key] = k["modulus"]

    kept.sort(key=lambda k: (k["rid"], k["index"], k["modulus"]))

    out = {
        "_comment": "Scheme Certification Authority (CA) public keys for offline CDA verification. "
                    "GENERATED by scripts/build_ca_public_keys.py — do not edit by hand; re-run the script. "
                    "Every key's 'checksum' = SHA-1(RID || index || modulus || exponent) was recomputed and "
                    "verified against the source before inclusion.",
        "_source": SOURCE_URL,
        "keys": kept,
    }
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
        fh.write("\n")

    print(f"kept {len(kept)} keys  |  hash-mismatch dropped {len(bad_hash)}  |  non-key lines skipped {skipped}")
    if bad_hash:
        for rid, index, pub, comp in bad_hash:
            print(f"  DROPPED bad hash RID {rid} index {index}: published {pub} != computed {comp}")
    if dupes:
        print(f"duplicate (RID,index) with differing moduli: {len(dupes)} group(s)")
        for (rid, index), mods in sorted(dupes.items()):
            print(f"  RID {rid} index {index}: {len(mods)} distinct keys")
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
